#Requires -RunAsAdministrator
<#
.SYNOPSIS
    applies the compiled dsc stig configuration to this node.

.DESCRIPTION
    calls Start-DscConfiguration against the mof generated by Bootstrap.ps1.
    waits for completion and logs the result.

    run Bootstrap.ps1 first if the mof has not yet been compiled.

.PARAMETER dscroot
    root path where the dsc zip was extracted. default: C:\DSC

.PARAMETER force
    re-applies all resources even if already in desired state. default: $true

.EXAMPLE
    .\Apply.ps1
    .\Apply.ps1 -Force $false
#>

[CmdletBinding()]
param (
    [string]$dscroot = 'C:\DSC',
    [bool]$force     = $true
)

Set-StrictMode -Version Latest
$erroractionpreference = 'Stop'

# ---------------------------------------------------------------------------
# logging plan to add to data analytics later - for now, just a timestamped log file in the dsc root. this will be helpful for troubleshooting and auditing, 
#and can be extended later to include more structured data or remote logging
# ---------------------------------------------------------------------------
$logdir  = Join-Path $dscroot 'Logs'
$null    = New-Item -ItemType Directory -Path $logdir -Force
$logfile = Join-Path $logdir "Apply_$(Get-Date -Format 'yyyyMMdd_HHmmss').log"

##### write-log: accepts a message string and optional level (info/warn/error). builds a timestamped entry string, appends it to the log file, then routes output to write-warning, write-error, or write-host depending on level #####
function Write-Log {
    param(
        [string]$message,
        [ValidateSet('info','warn','error')]
        [string]$level = 'info'
    )
    $entry = "[$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')] [$level] $message"
    Add-Content -Path $logfile -Value $entry
    switch ($level) {
        'warn'  { Write-Warning $entry }
        'error' { Write-Error   $entry }
        default { Write-Host    $entry }
    }
}

# ---------------------------------------------------------------------------
# main - thank god for ai here, this is a pretty straightforward script but the error handling and logging is a bit verbose. the main logic is just to find the mof 
#file and call Start-DscConfiguration with it, then test compliance afterward. the rest is just safety checks and logging.
# ---------------------------------------------------------------------------
try {
    Write-Log "========== apply started on $env:COMPUTERNAME =========="

    $mofpath = Join-Path $dscroot 'MOF'

    ##### check if the mof directory exists — if missing, bootstrap has not run yet, throw and abort before attempting to apply nothing #####
    if (-not (Test-Path $mofpath)) {
        throw "mof directory not found at '$mofpath'. run Bootstrap.ps1 first."
    }

    ##### scan the mof directory for a .mof file — selects the first match only, returns null if compilation never produced output #####
    $moffile = Get-ChildItem -Path $mofpath -Filter '*.mof' -ErrorAction SilentlyContinue |
               Select-Object -First 1

    ##### check if the mof file scan returned anything — if null, compilation never completed, throw and abort #####
    if (-not $moffile) {
        throw "no .mof file found in '$mofpath'. run Bootstrap.ps1 to compile the configuration."
    }

    Write-Log "applying mof: $($moffile.FullName)"
    Write-Log "force: $force"

    ##### splat Start-DscConfiguration parameters — path targets the mof directory, wait blocks the script until dsc finishes, 
    ##### force re-applies all resources even if already compliant. splat means passing a hashtable of parameters #####
    $params = @{
        Path    = $mofpath
        Wait    = $true
        Verbose = $true
        Force   = $force
    }

    Start-DscConfiguration @params

    ##### post-apply compliance check — tests the node against the same mof to confirm all resources landed in desired state. warns if not, as a pending reboot may be needed for some resources to settle #####
    $testresult = Test-DscConfiguration -Path $mofpath
    if ($testresult) {
        Write-Log "========== apply complete - node is in desired state =========="
    }
    else {
        Write-Log "apply finished but node is not fully in desired state. a reboot may be required." 'warn'
        Write-Log "if RebootNodeIfNeeded is true in lcm, the system will reboot and continue automatically." 'warn'
    }
}
catch {
    Write-Log "fatal error: $_" 'error'
    Write-Log "stack trace: $($_.ScriptStackTrace)" 'error'
    exit 1
}
