#Requires -RunAsAdministrator
<#
.SYNOPSIS
    Applies the compiled DSC STIG configuration to this node.

.DESCRIPTION
    Calls Start-DscConfiguration against the MOF generated by Bootstrap.ps1.
    Waits for completion and logs the result.

    Run Bootstrap.ps1 first if the MOF has not yet been compiled.

.PARAMETER DSCRoot
    Root path where the DSC ZIP was extracted. Default: C:\DSC

.PARAMETER Force
    Re-applies all resources even if already in desired state. Default: $true

.EXAMPLE
    .\Apply.ps1
    .\Apply.ps1 -Force $false
#>

[CmdletBinding()]
param (
    [string]$DSCRoot = 'C:\DSC',
    [bool]$Force     = $true
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
$LogDir  = Join-Path $DSCRoot 'Logs'
$null    = New-Item -ItemType Directory -Path $LogDir -Force
$LogFile = Join-Path $LogDir "Apply_$(Get-Date -Format 'yyyyMMdd_HHmmss').log"

function Write-Log {
    param(
        [string]$Message,
        [ValidateSet('INFO','WARN','ERROR')]
        [string]$Level = 'INFO'
    )
    $entry = "[$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')] [$Level] $Message"
    Add-Content -Path $LogFile -Value $entry
    switch ($Level) {
        'WARN'  { Write-Warning $entry }
        'ERROR' { Write-Error   $entry }
        default { Write-Host    $entry }
    }
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
try {
    Write-Log "========== Apply started on $env:COMPUTERNAME =========="

    $MofPath = Join-Path $DSCRoot 'MOF'

    if (-not (Test-Path $MofPath)) {
        throw "MOF directory not found at '$MofPath'. Run Bootstrap.ps1 first."
    }

    $MofFile = Get-ChildItem -Path $MofPath -Filter '*.mof' -ErrorAction SilentlyContinue |
               Select-Object -First 1

    if (-not $MofFile) {
        throw "No .mof file found in '$MofPath'. Run Bootstrap.ps1 to compile the configuration."
    }

    Write-Log "Applying MOF: $($MofFile.FullName)"
    Write-Log "Force: $Force"

    $params = @{
        Path    = $MofPath
        Wait    = $true
        Verbose = $true
        Force   = $Force
    }

    Start-DscConfiguration @params

    # Post-apply check
    $testResult = Test-DscConfiguration -Path $MofPath
    if ($testResult) {
        Write-Log "========== Apply complete — node is IN desired state =========="
    }
    else {
        Write-Log "Apply finished but node is NOT fully in desired state. A reboot may be required." 'WARN'
        Write-Log "If RebootNodeIfNeeded is true in LCM, the system will reboot and continue automatically." 'WARN'
    }
}
catch {
    Write-Log "FATAL ERROR: $_" 'ERROR'
    Write-Log "Stack trace: $($_.ScriptStackTrace)" 'ERROR'
    exit 1
}
