#Requires -RunAsAdministrator
<#
.SYNOPSIS
    applies the compiled dsc stig configuration to this node.

.DESCRIPTION
    calls Start-DscConfiguration against the mof generated by Bootstrap.ps1.
    waits for completion and logs the result.

    run Bootstrap.ps1 first if the mof has not yet been compiled.

.PARAMETER dscroot
    root path where the dsc zip was extracted. default: C:\DSC

.PARAMETER force
    re-applies all resources even if already in desired state. default: $true

.EXAMPLE
    .\Apply.ps1
    .\Apply.ps1 -Force $false
#>

[CmdletBinding()]
param (
    [string]$dscroot = 'C:\DSC',
    [bool]$force     = $true
)

Set-StrictMode -Version Latest
$erroractionpreference = 'Stop'

# ---------------------------------------------------------------------------
# logging
# ---------------------------------------------------------------------------
$logdir  = Join-Path $dscroot 'Logs'
$null    = New-Item -ItemType Directory -Path $logdir -Force
$logfile = Join-Path $logdir "Apply_$(Get-Date -Format 'yyyyMMdd_HHmmss').log"

function Write-Log {
    param(
        [string]$message,
        [ValidateSet('info','warn','error')]
        [string]$level = 'info'
    )
    $entry = "[$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')] [$level] $message"
    Add-Content -Path $logfile -Value $entry
    switch ($level) {
        'warn'  { Write-Warning $entry }
        'error' { Write-Error   $entry }
        default { Write-Host    $entry }
    }
}

# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------
try {
    Write-Log "========== apply started on $env:COMPUTERNAME =========="

    $mofpath = Join-Path $dscroot 'MOF'

    # abort if mof directory is missing — bootstrap must run first
    if (-not (Test-Path $mofpath)) {
        throw "mof directory not found at '$mofpath'. run Bootstrap.ps1 first."
    }

    # abort if no mof file exists inside the mof directory
    $moffile = Get-ChildItem -Path $mofpath -Filter '*.mof' -ErrorAction SilentlyContinue |
               Select-Object -First 1

    if (-not $moffile) {
        throw "no .mof file found in '$mofpath'. run Bootstrap.ps1 to compile the configuration."
    }

    Write-Log "applying mof: $($moffile.FullName)"
    Write-Log "force: $force"

    # splat parameters for Start-DscConfiguration for readability
    $params = @{
        Path    = $mofpath
        Wait    = $true
        Verbose = $true
        Force   = $force
    }

    Start-DscConfiguration @params

    # post-apply compliance check — warn if node is still out of state (may need reboot)
    $testresult = Test-DscConfiguration -Path $mofpath
    if ($testresult) {
        Write-Log "========== apply complete — node is in desired state =========="
    }
    else {
        Write-Log "apply finished but node is not fully in desired state. a reboot may be required." 'warn'
        Write-Log "if RebootNodeIfNeeded is true in lcm, the system will reboot and continue automatically." 'warn'
    }
}
catch {
    Write-Log "fatal error: $_" 'error'
    Write-Log "stack trace: $($_.ScriptStackTrace)" 'error'
    exit 1
}
